default: &default
  adapter: postgresql
  encoding: unicode
  database: <%= ENV.fetch('POSTGRES_DB') %>
  username: <%= ENV.fetch('POSTGRES_USER') %>
  password: <%= ENV.fetch('POSTGRES_PASSWORD') %>
  host: <%= ENV.fetch('POSTGRES_HOST') %>
  port: <%= ENV.fetch('POSTGRES_PORT') %>

test:
  <<: *default
