name: Ruby

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  rspec:
    runs-on: ubuntu-latest

    env:
      POSTGRES_DB: test_db
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432

    services:
      postgres:
        env:
          POSTGRES_DB: test_db
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
        image: postgres:14
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    strategy:
      matrix:
        ruby: [3.1, 3.2, 3.3]
        appraisal: ["activerecord-6.1", "activerecord-7.1"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Install Appraisals
      run: |
        bundle install
        bundle exec appraisal install

    - name: Run specs for ${{ matrix.appraisal }}
      run: bundle exec appraisal ${{ matrix.appraisal }} rspec
